version: "3.8"
services:
  backend:
    build: ./quiz_clicker_api
    container_name: quiz_clicker_api
    restart: always
    ports:
      - "8000:8000"

  frontend:
    build: ./quiz_clicker_ui
    container_name: quiz_clicker_ui
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
